from database import Base, SessionLocal, engine
from models import Listing, User

Base.metadata.create_all(bind=engine)

db = SessionLocal()

# Keep users, reset listings only
db.query(Listing).delete()
db.commit()

if db.query(User).count() == 0:
    users = [
        User(name="Theresa Al Achkar", email="admin@lu.edu", role="admin", status="active", join_date="2026-03-20"),
        User(name="Celine Al Dassouki", email="student@lu.edu", role="student", status="active", join_date="2026-03-22"),
        User(name="Pamela Kneyzeh", email="landlord@lu.edu", role="landlord", status="active", join_date="2026-03-25"),
        User(name="Agnes Rahal", email="agnes@lu.edu", role="landlord", status="inactive", join_date="2026-03-28"),
    ]
    db.add_all(users)

listings = [
    Listing(
        title="Shared Student Room – Hamra near AUB",
        type="Shared",
        price=280,
        location="Hamra, Beirut",
        distance="5 min walk from AUB",
        beds=1,
        baths=2,
        sqm=18,
        available="Immediate",
        amenities="WiFi,Shared Kitchen,Laundry,Furnished,Water Included",
        landlord_name="Hamra Student Residence",
        landlord_email="hamra.residence@example.com",
        landlord_phone="+96170111222",
        description="Affordable shared student room in Hamra, suitable for AUB and LAU students. Includes WiFi, shared kitchen, laundry access, and basic furniture.",
        rating=4.6,
        reviews=18,
        color="#1b4332",
        status="approved",
    ),
    Listing(
        title="Private Studio – Bliss Street",
        type="Studio",
        price=550,
        location="Bliss Street, Beirut",
        distance="2 min walk from AUB",
        beds=1,
        baths=1,
        sqm=28,
        available="June 2026",
        amenities="WiFi,Private Bathroom,Furnished,Kitchenette,Generator",
        landlord_name="Bliss Housing",
        landlord_email="bliss.housing@example.com",
        landlord_phone="+96171123456",
        description="Private furnished studio close to AUB campus. Ideal for students who prefer privacy and quick access to university facilities.",
        rating=4.8,
        reviews=12,
        color="#1e3a5f",
        status="approved",
    ),
    Listing(
        title="Female Dorm Room – LAU Beirut Area",
        type="Dorm",
        price=350,
        location="Koraytem, Beirut",
        distance="7 min walk from LAU Beirut",
        beds=1,
        baths=3,
        sqm=16,
        available="September 2026",
        amenities="WiFi,Furnished,Shared Kitchen,Security,Laundry",
        landlord_name="Koraytem Ladies Dorm",
        landlord_email="koraytem.dorm@example.com",
        landlord_phone="+96176111222",
        description="Student dorm room for female students near LAU Beirut. Safe building with shared services and easy access to Hamra and Koreitem.",
        rating=4.5,
        reviews=21,
        color="#4a1a6b",
        status="approved",
    ),
    Listing(
        title="Shared Apartment – Verdun",
        type="House Share",
        price=400,
        location="Verdun, Beirut",
        distance="12 min from LAU Beirut",
        beds=2,
        baths=1,
        sqm=65,
        available="Immediate",
        amenities="WiFi,Furnished,Kitchen,Balcony,Elevator",
        landlord_name="Verdun Student Flats",
        landlord_email="verdun.flats@example.com",
        landlord_phone="+96170444555",
        description="Shared furnished apartment in Verdun for two students. Calm residential area with nearby supermarkets, transportation, and university access.",
        rating=4.4,
        reviews=10,
        color="#7a3618",
        status="pending",
    ),
    Listing(
        title="Student Room – Hadath near Lebanese University",
        type="Shared",
        price=230,
        location="Hadath, Baabda",
        distance="8 min from Lebanese University Hadath Campus",
        beds=1,
        baths=2,
        sqm=17,
        available="Immediate",
        amenities="WiFi,Furnished,Shared Kitchen,Water Included,Parking",
        landlord_name="Hadath Student Housing",
        landlord_email="hadath.housing@example.com",
        landlord_phone="+96170888999",
        description="Budget-friendly student room close to Lebanese University Hadath campus. Suitable for LU students looking for affordable accommodation.",
        rating=4.3,
        reviews=15,
        color="#166534",
        status="approved",
    ),
    Listing(
        title="Small Studio – Choueifat / LU Access",
        type="Studio",
        price=320,
        location="Choueifat",
        distance="15 min from Lebanese University Hadath",
        beds=1,
        baths=1,
        sqm=24,
        available="July 2026",
        amenities="Private Bathroom,Furnished,Kitchenette,Water Included",
        landlord_name="Choueifat Rentals",
        landlord_email="choueifat.rentals@example.com",
        landlord_phone="+96171333444",
        description="Compact studio suitable for one student. Located in Choueifat with easy transportation access to Hadath and Beirut.",
        rating=4.1,
        reviews=8,
        color="#0f766e",
        status="pending",
    ),
    Listing(
        title="Room in Shared Flat – Achrafieh near USJ",
        type="House Share",
        price=420,
        location="Achrafieh, Beirut",
        distance="10 min from USJ",
        beds=1,
        baths=2,
        sqm=20,
        available="Immediate",
        amenities="WiFi,Furnished,Shared Kitchen,Elevator,Generator",
        landlord_name="Achrafieh Student Stay",
        landlord_email="achrafieh.stay@example.com",
        landlord_phone="+96176999000",
        description="Room in a shared furnished apartment in Achrafieh. Suitable for students studying at USJ, AUST, or universities in central Beirut.",
        rating=4.7,
        reviews=17,
        color="#92400e",
        status="approved",
    ),
    Listing(
        title="Budget Dorm Bed – Cola / Beirut Transport Hub",
        type="Dorm",
        price=180,
        location="Cola, Beirut",
        distance="Transport access to LU, AUB, LAU",
        beds=1,
        baths=4,
        sqm=14,
        available="Immediate",
        amenities="Shared Kitchen,WiFi,Furnished,Water Included",
        landlord_name="Cola Budget Dorms",
        landlord_email="cola.dorms@example.com",
        landlord_phone="+96170222111",
        description="Low-cost dorm bed suitable for students who need transportation access to several Beirut universities.",
        rating=4.0,
        reviews=19,
        color="#581c87",
        status="pending",
    ),
    Listing(
        title="Private Room – Fanar near LU Faculty Branches",
        type="Shared",
        price=260,
        location="Fanar, Metn",
        distance="Near LU Faculty branches and public transport",
        beds=1,
        baths=1,
        sqm=19,
        available="August 2026",
        amenities="WiFi,Furnished,Private Room,Shared Kitchen,Parking",
        landlord_name="Fanar Student Rooms",
        landlord_email="fanar.rooms@example.com",
        landlord_phone="+96171987654",
        description="Private student room in Fanar with shared kitchen and parking. Practical option for students studying in nearby LU branches.",
        rating=4.2,
        reviews=11,
        color="#365314",
        status="approved",
    ),
    Listing(
        title="Official-Style LAU Beirut Shared Housing",
        type="Dorm",
        price=1489,
        location="LAU Beirut Campus Area",
        distance="On/near LAU Beirut",
        beds=1,
        baths=3,
        sqm=16,
        available="Fall 2026",
        amenities="Security,Furnished,Campus Access,WiFi,Student Community",
        landlord_name="LAU Residence Office",
        landlord_email="housing@example-lau.edu",
        landlord_phone="+9611786456",
        description="Demo entry based on the idea of university residence housing near LAU Beirut. Official housing fees vary by academic year and room type.",
        rating=4.9,
        reviews=30,
        color="#064e3b",
        status="approved",
    ),
]

db.add_all(listings)
db.commit()
db.close()

print("Lebanon student housing database seeded successfully.")